### ISSUE TITLE
Integrate ion camera into ARTIQ experiment

### ISSUE THREAD

**Issue by CKevin9** [quantumion/PyVCAM#1]

**Comment by CKevin9** [comment]
See [PR1](https://github.com/quantumion/PyVCAM/pull/2)
Associated with ClickUp Task CU-2a7cqw7.

**Comment by collineps** [comment]
Closed by [666a8cb](https://github.com/quantumion/PyVCAM/commit/666a8cbce3eb3dad586ddb1fbf083e49bb975961).
